version: '2'

services:
  app:
    image: 'simonmontenegro/backend-mingeso:docker-mingeso'
    build: .
    ports:
      - 8082:8082
    container_name: backend
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/supermercado
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
          
  db:
    image: 'simonmontenegro/database-mingeso:docker-database'
    container_name: database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=supermercado
    volumes:
      - ./dbCreate.sql:/docker-entrypoint-initdb.d/dbCreate.sql